#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
# Taken from https://gist.github.com/ndarville/3625246

language: python


python:
  - 2.7

services:
  - postgresql
  - redis
  - elasticsearch

sudo: false

addons:
    postgresql: "9.4"
    apt:
       sources:
       - elasticsearch-2.x
       packages:
       - elasticsearch
       - python-requests
       - python-lxml
       - curl
       - libffi-dev
       - libssl-dev

env:
  global:
    - DJANGO=1.9.6
      # RoMEO API key
    - secure: "hQg8tso/Qv4zXhP4A2ahKKhFZQSariIvUr+xqzzoTVtuN/9OuzBFjZ1UF8atM5KKGZ47fFMK2wTjbVOWjSyLH/SF3Wy8bX9oHHg1P8bXcsle6O/tfa3U/2s0UiYtThEdxp+iyQIr6cjBA0gmB0v/vFrQot91GvjlUbi70Xjfcts="
      # Proaixy API key
    - secure: "FayAfdusZgzSsAc7HZaCSyhMiwr19Qk/ePmjcBk6HyVWW9EaJiokjMb2DAc9IlBmkZxNg1+DU+ou1L4thPNaFrkTBqtdjQdqNtzsycyMedD6gYGKAdhaOuHNaCkikRHcIR1+STxx2udzOC1yk8xocaYiQFBD6AmRveMGfGN3WZw="
      # Zenodo Sandbox API key
    - secure: "KjRrTKrNyhv1xVl2UBtJ/qH0uFGItvxw7/pGFfPrcwxD5YAB5daePDaIGe/tlVy+lrQi0D9x1CA8MB2vm+Lf4jrfO+3ZHCkmb4ecbumPV7DxEbgFsralBx65PRRVUiDW1Oy0RyigxXNNdtNLvTVr1PYrZYD407HZnP6LrJP0ONM="
      # Gitbot l10n key (for translation notifications)
    - secure: "qm+WAH7GpYIjid+q5tVnRgpiIwRmo7C8ou8GAeHJwTxkcmX8+YsYhuuacXO5mW/gcvjb9UNVCDkIKqjIsxJdmC0JovXJJ2dG2g1P39FfOCsF1+FpOqxdjBxdlJCoPb+Wmx7qk5+n+ZgqArgDPFwTWAPqsfshVPLplvaIYfA6H2s="
      # Codacy key
    - secure: "aJdfB9VrRsWutoQzzYeG1njGQhUMmD9MfiEEH/HOhktM9Bw+qm0klhNEzANgHzR+i7CXrd8IbHoTW3ehLxM0KIcbj6dwgY8qtCJyLHyqyJqS8axjhjdTkUV+61P7jDPTsR8FMGbTqHjo5VEDEbxcwZfGvcmQBvSX0sBsWygwjcY="


virtualenv:
  system_site_packages: true

before_install:
  - export DJANGO_SETTINGS_MODULE=dissemin.settings
  - export PYTHONPATH=$HOME/builds/wetneb/dissemin
  - export PIP_USE_MIRRORS=true
  - echo "from .travis import *" > dissemin/settings/__init__.py
  - cp dissemin/settings/secret_template.py dissemin/settings/secret.py

install:
  - pip install setuptools --upgrade
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - pip install -r requirements.txt
  - pip install codacy-coverage coverage
  - pip install pyflakes
  - ./pyflakes.sh

before_script:
  - psql --version
  - psql -c "CREATE DATABASE dissemin;" -U postgres

script:
  - ./devutils/notify_translations
  - coverage run --source=dissemin,papers,backend,deposit,upload,statistics --omit=*/migrations/*,dissemin/settings/* manage.py test -v 2

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml

notifications:
  irc:
    channels:
      - "ulminfo.fr#dissemin"
    on_success: never
    on_failure: never
